[2024-07-08T03:08:31.909+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T03:08:31.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.download_data scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T03:08:31.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.download_data scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T03:08:31.920+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T03:08:31.924+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data> on 2024-07-07 00:00:00+00:00
[2024-07-08T03:08:31.926+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T03:08:31.927+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-07-08T03:08:31.927+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'download_data', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmprgi5q9xf']
[2024-07-08T03:08:31.927+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask download_data
[2024-07-08T03:08:31.931+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-07-08T03:08:31.956+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.download_data scheduled__2024-07-07T00:00:00+00:00 [running]> on host 6e509916ff4a
[2024-07-08T03:08:31.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-08T03:08:31.989+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T03:08:37.148+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T03:08:37.149+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_dag.py", line 9, in download_data
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
[2024-07-08T03:08:37.164+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=download_data, run_id=scheduled__2024-07-07T00:00:00+00:00, execution_date=20240707T000000, start_date=20240708T030831, end_date=20240708T030837
[2024-07-08T03:08:37.175+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task download_data (Exceeded 30 redirects.; 64)
[2024-07-08T03:08:37.211+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T03:08:37.221+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T03:08:37.222+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
