[2024-07-08T02:50:26.858+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: collect_data.get_data_from_api scheduled__2024-07-01T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
